hugover: extended_0.122.0
serve:
  - key: default
    config: config.yaml
build:
  - key: default
    config: config.yaml
menu:
  - key: settings
    title: Settings
    menuItems:
      - key: mainConfig